import AppKit

/// Polls `NSPasteboard` for changes (macOS has no clipboard-change notification)
/// and reports new content via callbacks.
final class ClipboardMonitor {
    var onText: ((String, NSRunningApplication?) -> Void)?
    var onImage: ((Data, NSRunningApplication?) -> Void)?
    var onFiles: (([String], NSRunningApplication?) -> Void)?

    private var timer: Timer?
    private var lastChangeCount = 0
    private var skipNext = false

    func start() {
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Skip the next observed change — used so our own paste isn't re-captured.
    func ignoreNextChange() { skipNext = true }

    /// Marker types set by password managers and other apps (nspasteboard.org
    /// convention) whose content must never be recorded.
    static let sensitiveMarkerTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",      // passwords / secrets
        "org.nspasteboard.TransientType",      // not meant to be stored
        "org.nspasteboard.AutoGeneratedType",  // programmatic, not user copies
        "com.agilebits.onepassword",           // legacy 1Password marker
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    static func isSensitive(types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return false }
        return types.contains { sensitiveMarkerTypes.contains($0.rawValue) }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if skipNext {
            skipNext = false
            return
        }
        // Honor concealed/transient markers so password-manager copies are
        // never captured, let alone written to disk.
        if Self.isSensitive(types: pb.types) { return }

        let app = NSWorkspace.shared.frontmostApplication

        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            onFiles?(urls.map(\.path), app)
        } else if let string = pb.string(forType: .string),
                  !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            onText?(string, app)
        } else if let data = pb.data(forType: .tiff) ?? pb.data(forType: .png) {
            onImage?(pngData(from: data) ?? data, app)
        }
    }

    private func pngData(from data: Data) -> Data? {
        NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:])
    }
}
